### ISSUE TITLE
Get more user profile info

### ISSUE THREAD

**Issue by slivorezka** [drupalsocialinitiative/social_auth_facebook#1]
Hi,

In general we can get the next user profile fields: **id**, **name** and **email**.

But I would like suggest get more info about a user like: 
**first_name**, **last_name**, **gender**, **birthday**, etc.
See more information about available Facebook fields here
https://developers.facebook.com/docs/graph-api/reference/v2.8/user (it is last version Graph API)

You need do a simple code update.
This field on the path: social_auth_facebook/src/FacebookAuthFbManager.php

`return $this->facebook->get('/me?fields=id,name,email')->getGraphNode();`

Update to (e.g.):

`return $this->facebook->get('/me?fields=id,name,email,first_name,last_name,gender,birthday, __some_field__')->getGraphNode();`

Thanks!

**Comment by gvso** [comment]
Hi @slivorezka
Why would we need to get more info about the user if we are not storing all the data in the database?

**Comment by slivorezka** [comment]
Hi @GVSO,
Yes, we are not storing all the data in the database.
But sometimes a developer need get this additional info,
And I think we can implement these additional fields in the settings of the module.
For example: 
These fields by default `id, name, email`
And these fields `first_name, last_name, gender, birthday` (maybe more fields) will optionally.

**Comment by gvso** [comment]
However, I don't see why you would ask for data that you are not storing. Furthermore, if another module wants to get more information, it might just need to ask for it.

I understand your intention of getting more information from the user, but it does not make any sense to me to do so if you don't store the data.

**Comment by gvso** [comment]
Social Auth Facebook 2.x allows websites to make initial requests and store the returned values in the database, so this issue is outdated.
