### ISSUE TITLE
Drupal disabled roles gets NULL

### ISSUE THREAD

**Issue by slivorezka** [drupalsocialinitiative/social_auth_facebook#2]
Hi,

I found a bug.

In the method **loginDisabledByRole** of class **FacebookAuthUserManager** 
(path: social_auth_facebook/src/FacebookAuthUserManager.php)

More detail about the bug:

If system does'n have disabled roles the var  `$disabled_roles` will get `NULL`.
But function `array_key_exists()` must get 2 argument as `array`. 
If it get `NULL` we will get message _Warning_.

You need add extra check this variable `$disabled_roles` like:

`if (!empty($disabled_roles) && array_key_exists($role, $disabled_roles) && ($disabled_roles[$role] !== 0))`

Thanks!

**Comment by gvso** [comment]
This implementation was changed in 2.x, so this issue is outdated
