### ISSUE TITLE
Facebook API seems to have a versioning problem

### ISSUE THREAD

**Issue by Paku-** [drupalsocialinitiative/social_auth_facebook#6]
using DEV 2.x

League\OAuth2\Client\Provider\Exception\IdentityProviderException: OAuthException: (#12) bio field is deprecated for versions v2.8 and higher w League\OAuth2\Client\Provider\Facebook->checkResponse() (linia 156 w /home/paku/ftp/webs/drupal8/vendor/league/oauth2-facebook/src/Provider/Facebook.php).

**Comment by gvso** [comment]
Can you please create an issue in drupal.org explaining the error in more detail?

**Comment by himanshu-dixit** [comment]
@Paku- Thanks for reporting it, You need to mention Graph API version as 2.9. This is an unusual error, I will create an issue for this on drupal.org and add more info about this in the documentation.

**Comment by Paku-** [comment]
Once API changed to 2.9, error vanished.

Getting

` Facebook login failed. This site requires permission to get your email address.`

now but it's my config error, I think

**Comment by Paku-** [comment]
Hava found that minimum API version to be configured using FB developer interface is 2.10.
The problem is that module's config form does not accept 2.10 nor 2,10. Any 2.10 like input is changed to 2,1 (??) Could be the it's field formatting error. I use european browser settings.

**Comment by Paku-** [comment]
It should be a text not decimal field. Decimal 2.10 and 2.1 is the same. Talking text - 2.1 and 2.10 are not.

**Comment by gvso** [comment]
Yes. This issue was [solved for 8.x-1.x](https://www.drupal.org/node/2895870) in the past

**Comment by Paku-** [comment]
Does it mean 2.0 is not stable 1.0 based ??

**Comment by gvso** [comment]
I guess @himanshu-dixit should be able to answer this more accurately, but I'd say that it is based on 1.x. However, the string field for the Graph API version was introduced while Himanshu was working on 2.x, and he probably forgot to merge the changes.

**Comment by Paku-** [comment]
So ? Can anybodu patch the 2.x ?

**Comment by gvso** [comment]
Fixed with PR #8
