### ISSUE TITLE
Composer install installs the /.git folder

### ISSUE THREAD

**Issue by Paku-** [drupalsocialinitiative/social_auth_facebook#7]
Hi guys,

It seems the 

`composer require drupal/social_auth_facebook `
(same for social_auth_google)

installs the /.git folder inside the module folder.

Is this the expected behaviour ?

I'm asking as it brakes my whole site backup using the git.

**Comment by gvso** [comment]
This is not specific to Social API. This probably happens when you run the command inside the modules folder and not in the drupal root directory

**Comment by gvso** [comment]
No updates on this, and nobody else reported something similar.
